"""
Filename: app/services/ai/gemini_provider.py
Description: Google Gemini concrete implementation of the AIProvider Strategy.
"""

import os
import google.generativeai as genai
from app.services.ai.base import AIProvider


class GeminiProvider(AIProvider):
    """Concrete provider strategy for communicating with Google Gemini API."""

    def __init__(self, model_name: str = "gemini-1.5-flash"):
        """
        Initialize GeminiProvider with specified model name and configure API key.

        Args:
            model_name: Name of the Gemini model to use (default: gemini-1.5-flash).
        """
        self.model_name = model_name
        api_key = os.getenv("GEMINI_API_KEY")
        genai.configure(api_key=api_key)

    def analyze(self, prompt: str) -> str:
        """
        Generate analysis using Google Gemini API.

        Args:
            prompt: Structured request prompt.

        Returns:
            str: Raw text generated by Gemini, or empty string if none.
        """
        model = genai.GenerativeModel(self.model_name)
        response = model.generate_content(prompt)
        if response and hasattr(response, "text") and response.text:
            return response.text
        return ""

    def generate(self, prompt: str) -> str:
        """
        Alias method for analyze.

        Args:
            prompt: Structured request prompt.

        Returns:
            str: Output from analyze(prompt).
        """
        return self.analyze(prompt)
