"""
Filename: app/services/ai/gemini_provider.py
Description: Google Gemini concrete implementation of the AIProvider Strategy.
"""

import os
from google import genai
from google.genai import types
from app.services.ai.base import AIProvider


class GeminiProvider(AIProvider):
    """Concrete provider strategy for communicating with Google Gemini API."""

    def __init__(self, model_name: str = None, api_key: str = None):
        """
        Initialize GeminiProvider with specified model name and configure API key.

        Args:
            model_name: Optional name of the Gemini model.
            api_key: Optional API key.
        """
        self._model_name = model_name
        self._api_key = api_key

    def _get_api_key(self) -> str:
        if self._api_key:
            return self._api_key
        try:
            from flask import current_app
            if current_app and current_app.config.get("GEMINI_API_KEY"):
                return current_app.config.get("GEMINI_API_KEY")
        except Exception:
            pass
        return os.getenv("GEMINI_API_KEY", "")

    def _get_model_name(self) -> str:
        if self._model_name:
            return self._model_name
        try:
            from flask import current_app
            if current_app and current_app.config.get("MODEL_NAME"):
                return current_app.config.get("MODEL_NAME")
        except Exception:
            pass
        return os.getenv("MODEL_NAME", "gemini-1.5-flash")

    @property
    def model_name(self) -> str:
        return self._get_model_name()

    def analyze(self, prompt: str) -> str:
        """
        Generate analysis using Google Gemini API.

        Args:
            prompt: Structured request prompt.

        Returns:
            str: Raw text generated by Gemini, or empty string if none.
        """
        api_key = self._get_api_key()
        client = genai.Client(api_key=api_key) if api_key else genai.Client()
        response = client.models.generate_content(
            model=self.model_name,
            contents=prompt,
        )

        try:
            if response and hasattr(response, "text") and response.text:
                return response.text
        except (ValueError, AttributeError):
            return ""
        return ""

    def generate(self, prompt: str) -> str:
        """
        Alias method for analyze.

        Args:
            prompt: Structured request prompt.

        Returns:
            str: Output from analyze(prompt).
        """
        return self.analyze(prompt)
