"""
Filename: app/services/ai/ollama_provider.py
Description: Ollama concrete implementation of the AIProvider Strategy.
"""

import requests
from flask import current_app
from app.services.ai.base import AIProvider

class OllamaProvider(AIProvider):
    """Concrete provider strategy for communicating with a local Ollama server."""

    def analyze(self, prompt: str) -> str:
        """
        Generate analysis using the local Ollama daemon.
        
        Args:
            prompt: Structured request prompt.
            
        Returns:
            str: Raw text generated by Ollama.
        """
        base_url = current_app.config.get("OLLAMA_BASE_URL", "http://localhost:11434")
        model = current_app.config.get("MODEL_NAME", "codellama:python")
        
        url = f"{base_url}/api/generate"
        payload = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }
        
        try:
            response = requests.post(url, json=payload, timeout=60)
            response.raise_for_status()
            data = response.json()
            return data.get("response", "")
        except requests.exceptions.RequestException as e:
            raise Exception(f"Ollama API request failed: {str(e)}")
